// This is an Unreal Script
//This class will mostly be used to make it so the default schematics are not buildable.
class X2Item_Schematics extends X2Item;

static function array<X2DataTemplate> CreateTemplates()
{
	local array<X2DataTemplate> Schematics;

	Schematics.AddItem(CreateTemplate_VektorRifle_Magnetic_Schematic());
	Schematics.AddItem(CreateTemplate_VektorRifle_Beam_Schematic());

	Schematics.AddItem(CreateTemplate_Bullpup_Magnetic_Schematic());
	Schematics.AddItem(CreateTemplate_Bullpup_Beam_Schematic());

	Schematics.AddItem(CreateTemplate_WristBlade_Magnetic_Schematic());
	Schematics.AddItem(CreateTemplate_WristBlade_Beam_Schematic());

	Schematics.AddItem(CreateTemplate_ShardGauntlet_Magnetic_Schematic());
	Schematics.AddItem(CreateTemplate_ShardGauntlet_Beam_Schematic());

	Schematics.AddItem(CreateTemplate_Sidearm_Magnetic_Schematic());
	Schematics.AddItem(CreateTemplate_Sidearm_Beam_Schematic());

	return Schematics;
}

// **************************************************************************
// ***                       Weapon Schematics                            ***
// **************************************************************************

static function X2DataTemplate CreateTemplate_VektorRifle_Magnetic_Schematic()
{
	local X2SchematicTemplate Template;
	local ArtifactCost Resources;

	`CREATE_X2TEMPLATE(class'X2SchematicTemplate', Template, 'VektorRifle_MG_Schematic');

	Template.ItemCat = 'weapon';
//BEGIN AUTOGENERATED CODE: Template Overrides 'VektorRifle_MG_Schematic'
	Template.strImage = "img:///UILibrary_XPACK_StrategyImages.Inv_MagVektor";
//END AUTOGENERATED CODE: Template Overrides 'VektorRifle_MG_Schematic'
	Template.PointsToComplete = 0;
	Template.Tier = 2;

	// Requirements
	Template.Requirements.RequiredTechs.AddItem('GaussWeapons');
	Template.Requirements.RequiredEngineeringScore = 15;
	Template.Requirements.bVisibleIfPersonnelGatesNotMet = true;

	Template.CanBeBuilt = false;

	// Cost
	Resources.ItemTemplateName = 'Supplies';
    Resources.Quantity = 40;
	Template.Cost.ResourceCosts.AddItem(Resources);

	Resources.ItemTemplateName = 'AlienAlloy';
    Resources.Quantity = 5;
	Template.Cost.ResourceCosts.AddItem(Resources);

	return Template;
}

static function X2DataTemplate CreateTemplate_VektorRifle_Beam_Schematic()
{
	local X2SchematicTemplate Template;
	local ArtifactCost Resources;

	`CREATE_X2TEMPLATE(class'X2SchematicTemplate', Template, 'VektorRifle_BM_Schematic');

	Template.ItemCat = 'weapon';
//BEGIN AUTOGENERATED CODE: Template Overrides 'VektorRifle_BM_Schematic'
	Template.strImage = "img:///UILibrary_XPACK_StrategyImages.Inv_BeamVektor";
//END AUTOGENERATED CODE: Template Overrides 'VektorRifle_BM_Schematic'
	Template.PointsToComplete = 0;
	Template.Tier = 4;


	// Requirements
	Template.Requirements.RequiredTechs.AddItem('PlasmaSniper');
	Template.Requirements.RequiredEngineeringScore = 25;
	Template.Requirements.bVisibleIfPersonnelGatesNotMet = true;

	Template.CanBeBuilt = false;

	// Cost
	Resources.ItemTemplateName = 'Supplies';
    Resources.Quantity = 1100;
	Template.Cost.ResourceCosts.AddItem(Resources);

	Resources.ItemTemplateName = 'AlienAlloy';
    Resources.Quantity = 7;
	Template.Cost.ResourceCosts.AddItem(Resources);

	Resources.ItemTemplateName = 'EleriumDust';
    Resources.Quantity = 7;
	Template.Cost.ResourceCosts.AddItem(Resources);

	return Template;
}

static function X2DataTemplate CreateTemplate_Bullpup_Magnetic_Schematic()
{
	local X2SchematicTemplate Template;
	local ArtifactCost Resources;

	`CREATE_X2TEMPLATE(class'X2SchematicTemplate', Template, 'Bullpup_MG_Schematic');

	Template.ItemCat = 'weapon';
//BEGIN AUTOGENERATED CODE: Template Overrides 'Bullpup_MG_Schematic'
	Template.strImage = "img:///UILibrary_XPACK_StrategyImages.Inv_MagSMG";
//END AUTOGENERATED CODE: Template Overrides 'Bullpup_MG_Schematic'
	Template.PointsToComplete = 0;
	Template.Tier = 1;


	// Requirements
	Template.Requirements.RequiredTechs.AddItem('MagnetizedWeapons');
	Template.Requirements.RequiredEngineeringScore = 15;
	Template.Requirements.bVisibleIfPersonnelGatesNotMet = true;

	Template.CanBeBuilt = false;

	// Cost
	Resources.ItemTemplateName = 'Supplies';
    Resources.Quantity = 45;
	Template.Cost.ResourceCosts.AddItem(Resources);

	Resources.ItemTemplateName = 'AlienAlloy';
    Resources.Quantity = 5;
	Template.Cost.ResourceCosts.AddItem(Resources);

	return Template;
}

static function X2DataTemplate CreateTemplate_Bullpup_Beam_Schematic()
{
	local X2SchematicTemplate Template;
	local ArtifactCost Resources;

	`CREATE_X2TEMPLATE(class'X2SchematicTemplate', Template, 'Bullpup_BM_Schematic');

	Template.ItemCat = 'weapon';
//BEGIN AUTOGENERATED CODE: Template Overrides 'Bullpup_BM_Schematic'
	Template.strImage = "img:///UILibrary_XPACK_StrategyImages.Inv_BeamSMG";
//END AUTOGENERATED CODE: Template Overrides 'Bullpup_BM_Schematic'
	Template.PointsToComplete = 0;
	Template.Tier = 3;


	// Requirements
	Template.Requirements.RequiredTechs.AddItem('PlasmaRifle');
	Template.Requirements.RequiredEngineeringScore = 25;

	Template.CanBeBuilt = false;

	// Cost
	Resources.ItemTemplateName = 'Supplies';
    Resources.Quantity = 90;
	Template.Cost.ResourceCosts.AddItem(Resources);

	Resources.ItemTemplateName = 'AlienAlloy';
    Resources.Quantity = 10;
	Template.Cost.ResourceCosts.AddItem(Resources);

	Resources.ItemTemplateName = 'EleriumDust';
    Resources.Quantity = 5;
	Template.Cost.ResourceCosts.AddItem(Resources);

	return Template;
}

static function X2DataTemplate CreateTemplate_WristBlade_Magnetic_Schematic()
{
	local X2SchematicTemplate Template;
	local ArtifactCost Resources;

	`CREATE_X2TEMPLATE(class'X2SchematicTemplate', Template, 'WristBlade_MG_Schematic');

	Template.ItemCat = 'weapon';
//BEGIN AUTOGENERATED CODE: Template Overrides 'WristBlade_MG_Schematic'
	Template.strImage = "img:///UILibrary_XPACK_StrategyImages.Inv_MagSGauntlet";
//END AUTOGENERATED CODE: Template Overrides 'WristBlade_MG_Schematic'
	Template.PointsToComplete = 0;
	Template.Tier = 1;

	// Requirements
	Template.Requirements.RequiredTechs.AddItem('AutopsyAdventStunLancer');
	Template.Requirements.RequiredEngineeringScore = 10;
	Template.Requirements.bVisibleIfPersonnelGatesNotMet = true;

	Template.CanBeBuilt = false;

	// Cost
	Resources.ItemTemplateName = 'Supplies';
    Resources.Quantity = 30;
	Template.Cost.ResourceCosts.AddItem(Resources);

	Resources.ItemTemplateName = 'AlienAlloy';
    Resources.Quantity = 3;
	Template.Cost.ResourceCosts.AddItem(Resources);

	return Template;
}

static function X2DataTemplate CreateTemplate_WristBlade_Beam_Schematic()
{
	local X2SchematicTemplate Template;
	local ArtifactCost Resources;

	`CREATE_X2TEMPLATE(class'X2SchematicTemplate', Template, 'WristBlade_BM_Schematic');

	Template.ItemCat = 'weapon';
//BEGIN AUTOGENERATED CODE: Template Overrides 'WristBlade_BM_Schematic'
	Template.strImage = "img:///UILibrary_XPACK_StrategyImages.Inv_BeamSGauntlet";
//END AUTOGENERATED CODE: Template Overrides 'WristBlade_BM_Schematic'
	Template.PointsToComplete = 0;
	Template.Tier = 3;

	// Requirements
	Template.Requirements.RequiredTechs.AddItem('AutopsyArchon');
	Template.Requirements.RequiredEngineeringScore = 20;
	Template.Requirements.bVisibleIfPersonnelGatesNotMet = true;

	Template.CanBeBuilt = false;
	Template.HideIfResearched = 'AutopsyArchon';

	// Cost
	Resources.ItemTemplateName = 'Supplies';
    Resources.Quantity = 60;
	Template.Cost.ResourceCosts.AddItem(Resources);

	Resources.ItemTemplateName = 'AlienAlloy';
    Resources.Quantity = 5;
	Template.Cost.ResourceCosts.AddItem(Resources);

	Resources.ItemTemplateName = 'EleriumDust';
    Resources.Quantity = 3;
	Template.Cost.ResourceCosts.AddItem(Resources);

	return Template;
}

static function X2DataTemplate CreateTemplate_ShardGauntlet_Magnetic_Schematic()
{
	local X2SchematicTemplate Template;
	local ArtifactCost Resources;

	`CREATE_X2TEMPLATE(class'X2SchematicTemplate', Template, 'ShardGauntlet_MG_Schematic');

	Template.ItemCat = 'weapon';
//BEGIN AUTOGENERATED CODE: Template Overrides 'ShardGauntlet_MG_Schematic'
	Template.strImage = "img:///UILibrary_XPACK_StrategyImages.Inv_MagTGauntlet";
//END AUTOGENERATED CODE: Template Overrides 'ShardGauntlet_MG_Schematic'
	Template.PointsToComplete = 0;
	Template.Tier = 2;


	// Requirements
	Template.Requirements.RequiredTechs.AddItem('PlatedArmor');
	Template.Requirements.RequiredEngineeringScore = 15;
	Template.Requirements.bVisibleIfPersonnelGatesNotMet = true;

	Template.CanBeBuilt = false;

	// Cost
	Resources.ItemTemplateName = 'Supplies';
    Resources.Quantity = 40;
	Template.Cost.ResourceCosts.AddItem(Resources);

	Resources.ItemTemplateName = 'AlienAlloy';
    Resources.Quantity = 5;
	Template.Cost.ResourceCosts.AddItem(Resources);

	return Template;
}

static function X2DataTemplate CreateTemplate_ShardGauntlet_Beam_Schematic()
{
	local X2SchematicTemplate Template;
	local ArtifactCost Resources;

	`CREATE_X2TEMPLATE(class'X2SchematicTemplate', Template, 'ShardGauntlet_BM_Schematic');

	Template.ItemCat = 'weapon';
//BEGIN AUTOGENERATED CODE: Template Overrides 'ShardGauntlet_BM_Schematic'
	Template.strImage = "img:///UILibrary_XPACK_StrategyImages.Inv_BeamTGauntlet";
//END AUTOGENERATED CODE: Template Overrides 'ShardGauntlet_BM_Schematic'
	Template.PointsToComplete = 0;
	Template.Tier = 4;


	// Requirements
	Template.Requirements.RequiredTechs.AddItem('PoweredArmor');
	Template.Requirements.RequiredEngineeringScore = 25;
	Template.Requirements.bVisibleIfPersonnelGatesNotMet = true;

	Template.CanBeBuilt = false;

	// Cost
	Resources.ItemTemplateName = 'Supplies';
    Resources.Quantity = 125;
	Template.Cost.ResourceCosts.AddItem(Resources);

	Resources.ItemTemplateName = 'AlienAlloy';
    Resources.Quantity = 5;
	Template.Cost.ResourceCosts.AddItem(Resources);

	Resources.ItemTemplateName = 'EleriumDust';
    Resources.Quantity = 10;
	Template.Cost.ResourceCosts.AddItem(Resources);

	return Template;
}

static function X2DataTemplate CreateTemplate_Sidearm_Magnetic_Schematic()
{
	local X2SchematicTemplate Template;
	local ArtifactCost Resources;

	`CREATE_X2TEMPLATE(class'X2SchematicTemplate', Template, 'Sidearm_MG_Schematic');

	Template.ItemCat = 'weapon';
//BEGIN AUTOGENERATED CODE: Template Overrides 'Sidearm_MG_Schematic'
	Template.strImage = "img:///UILibrary_XPACK_StrategyImages.Inv_MagTPistol_Base";
//END AUTOGENERATED CODE: Template Overrides 'Sidearm_MG_Schematic'
	Template.PointsToComplete = 0;
	Template.Tier = 1;

	// Requirements
	Template.Requirements.RequiredTechs.AddItem('MagnetizedWeapons');
	Template.Requirements.RequiredEngineeringScore = 10;
	Template.Requirements.RequiredSoldierClass = 'Templar';
	Template.Requirements.bVisibleIfPersonnelGatesNotMet = true;

	Template.CanBeBuilt = false;

	// Cost
	Resources.ItemTemplateName = 'Supplies';
    Resources.Quantity = 25;
	Template.Cost.ResourceCosts.AddItem(Resources);

	Resources.ItemTemplateName = 'AlienAlloy';
    Resources.Quantity = 2;
	Template.Cost.ResourceCosts.AddItem(Resources);

	return Template;
}

static function X2DataTemplate CreateTemplate_Sidearm_Beam_Schematic()
{
	local X2SchematicTemplate Template;
	local ArtifactCost Resources;

	`CREATE_X2TEMPLATE(class'X2SchematicTemplate', Template, 'Sidearm_BM_Schematic');

	Template.ItemCat = 'weapon';
//BEGIN AUTOGENERATED CODE: Template Overrides 'Sidearm_BM_Schematic'
	Template.strImage = "img:///UILibrary_XPACK_StrategyImages.Inv_BeamTPistol_Base";
//END AUTOGENERATED CODE: Template Overrides 'Sidearm_BM_Schematic'
	Template.PointsToComplete = 0;
	Template.Tier = 3;

	// Reference Item

	// Requirements
	Template.Requirements.RequiredTechs.AddItem('PlasmaRifle');
	Template.Requirements.RequiredEngineeringScore = 20;
	Template.Requirements.RequiredSoldierClass = 'Templar';
	Template.Requirements.bVisibleIfPersonnelGatesNotMet = true;

	Template.CanBeBuilt = false;

	// Cost
	Resources.ItemTemplateName = 'Supplies';
    Resources.Quantity = 40;
	Template.Cost.ResourceCosts.AddItem(Resources);

	Resources.ItemTemplateName = 'AlienAlloy';
    Resources.Quantity = 5;
	Template.Cost.ResourceCosts.AddItem(Resources);

	Resources.ItemTemplateName = 'EleriumDust';
    Resources.Quantity = 3;
	Template.Cost.ResourceCosts.AddItem(Resources);

	return Template;
}